# Generated by Django 2.1.2 on 2018-10-29 21:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ToDo', '0002_auto_20181029_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='share',
            field=models.ManyToManyField(related_name='_todo_share_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
