# Generated by Django 2.1.2 on 2018-10-29 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0003_todo_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='owner',
        ),
    ]
