# Generated by Django 2.1.2 on 2018-10-29 21:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0004_remove_todo_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='share',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
