# Generated by Django 2.1.2 on 2018-10-29 21:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0005_auto_20181029_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='share',
            field=models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
