# Generated by Django 2.1.2 on 2018-10-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0008_auto_20181029_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='attachment',
            field=models.FileField(default='', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
