# Generated by Django 2.1.2 on 2018-10-30 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0011_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='coments',
        ),
        migrations.AddField(
            model_name='todo',
            name='comments',
            field=models.ManyToManyField(related_name='comment', to='ToDo.Comment'),
        ),
    ]
