# Generated by Django 2.1.2 on 2018-10-30 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0012_auto_20181030_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coment',
            name='author',
        ),
        migrations.DeleteModel(
            name='Coment',
        ),
    ]
