# Generated by Django 2.1.2 on 2018-10-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0013_auto_20181030_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='attachment',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
