# Generated by Django 2.1.2 on 2018-10-30 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0014_comment_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comment', to='ToDo.Comment'),
        ),
    ]
